'use client'

import { useState, useEffect, Suspense } from 'react'
import { useSearchParams } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent } from '@/components/ui/card'
import { getSeasonLabel } from '@/lib/ai/season'

const INDIAN_DESTINATIONS = [
  'Goa', 'Manali', 'Jaipur', 'Kerala', 'Ladakh', 'Andaman', 'Varanasi', 'Rishikesh',
  'Shimla', 'Ooty', 'Coorg', 'Munnar', 'Darjeeling', 'Spiti', 'Rann of Kutch',
  'Jim Corbett', 'Hampi', 'Mysore', 'Udaipur', 'Jodhpur',
]

const SEASONS = ['Summer (Mar-Jun)', 'Monsoon (Jul-Sep)', 'Winter (Oct-Feb)']

type Category = {
  name: string
  icon: string
  items: string[]
}

type PackingData = {
  categories: Category[]
  tips: string[]
}

function deriveSeason(startDate: string): string {
  try {
    const label = getSeasonLabel(startDate)
    // Map to packing list dropdown values
    if (label.includes('Monsoon')) return 'Monsoon (Jul-Sep)'
    if (label.includes('Summer'))  return 'Summer (Mar-Jun)'
    return 'Winter (Oct-Feb)'
  } catch { return 'Winter (Oct-Feb)' }
}

function deriveTravelers(group: string, style: string): string {
  const n = parseInt(group || '1')
  if (style === 'family') return 'Family with kids'
  if (n === 1) return 'Solo'
  if (n === 2) return 'Couple'
  return 'Group of friends'
}

function deriveTripType(style: string): string {
  if (style === 'adventure') return 'Adventure'
  if (style === 'family')    return 'Heritage/City'
  if (style === 'luxury')    return 'Heritage/City'
  return 'Beach'
}

function PackingListInner() {
  const searchParams = useSearchParams()

  const startDate  = searchParams.get('start_date') || ''
  const styleParam = searchParams.get('style') || ''
  const groupParam = searchParams.get('group') || '1'

  const [destination, setDestination] = useState(searchParams.get('destination') || '')
  const [days,        setDays]        = useState(searchParams.get('days') || '5')
  const [tripType,    setTripType]    = useState(deriveTripType(styleParam))
  const [season,      setSeason]      = useState(startDate ? deriveSeason(startDate) : 'Winter (Oct-Feb)')
  const [travelers,   setTravelers]   = useState(deriveTravelers(groupParam, styleParam))
  const [loading,     setLoading]     = useState(false)
  const [result,      setResult]      = useState<PackingData | null>(null)
  const [checked,     setChecked]     = useState<Record<string, boolean>>({})
  const [error,       setError]       = useState('')

  useEffect(() => {
    if (searchParams.get('destination') && searchParams.get('auto') === '1') {
      generate()
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  async function generate() {
    if (!destination.trim()) {
      setError('Please enter a destination.')
      return
    }
    setError('')
    setLoading(true)
    setResult(null)
    setChecked({})
    try {
      const res = await fetch('/api/ai/packing-list', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ destination, days: Number(days), tripType, season, travelers }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error || 'Failed')
      setResult(data)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Failed to generate packing list. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  function toggleItem(key: string) {
    setChecked(prev => ({ ...prev, [key]: !prev[key] }))
  }

  const checkedCount = Object.values(checked).filter(Boolean).length
  const totalItems   = result?.categories.reduce((s, c) => s + c.items.length, 0) ?? 0

  function buildWhatsAppText() {
    if (!result) return ''
    const lines: string[] = [`🎒 Packing List for ${destination} (${days} days - ${tripType})\n`]
    for (const cat of result.categories) {
      lines.push(`${cat.icon} ${cat.name}`)
      for (const item of cat.items) lines.push(`  • ${item}`)
      lines.push('')
    }
    if (result.tips.length) {
      lines.push('💡 Tips')
      for (const tip of result.tips) lines.push(`  • ${tip}`)
    }
    lines.push('\nGenerated by TripWise — https://tripwise.in')
    return encodeURIComponent(lines.join('\n'))
  }

  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <div className="text-center mb-10">
        <h1 className="text-3xl sm:text-4xl font-extrabold text-gray-900 mb-2">
          🎒 Smart Packing List Generator
        </h1>
        <p className="text-gray-500 text-base">AI generates a personalised packing list for your trip</p>
      </div>

      <Card className="shadow-md border-0 mb-8">
        <CardContent className="p-6 space-y-5">
          <div className="space-y-1.5">
            <Label htmlFor="destination" className="text-sm font-medium text-gray-700">Destination</Label>
            <Input
              id="destination"
              list="dest-list"
              placeholder="e.g. Goa, Manali, Kerala"
              value={destination}
              onChange={e => setDestination(e.target.value)}
              className="h-11"
            />
            <datalist id="dest-list">
              {INDIAN_DESTINATIONS.map(d => <option key={d} value={d} />)}
            </datalist>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label htmlFor="days" className="text-sm font-medium text-gray-700">Duration (days)</Label>
              <Input
                id="days"
                type="number"
                min={1}
                max={30}
                value={days}
                onChange={e => setDays(e.target.value)}
                className="h-11"
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="tripType" className="text-sm font-medium text-gray-700">Trip Type</Label>
              <select
                id="tripType"
                value={tripType}
                onChange={e => setTripType(e.target.value)}
                className="w-full h-11 border border-input bg-background rounded-md px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
              >
                {['Beach', 'Mountains', 'Heritage/City', 'Wildlife', 'Adventure', 'Spiritual', 'Business'].map(t => (
                  <option key={t} value={t}>{t}</option>
                ))}
              </select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label htmlFor="season" className="text-sm font-medium text-gray-700">
                Season
                {startDate && <span className="ml-1 text-xs text-blue-500 font-normal">(auto-detected)</span>}
              </Label>
              <select
                id="season"
                value={season}
                onChange={e => setSeason(e.target.value)}
                className="w-full h-11 border border-input bg-background rounded-md px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
              >
                {SEASONS.map(s => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="travelers" className="text-sm font-medium text-gray-700">Travelers</Label>
              <select
                id="travelers"
                value={travelers}
                onChange={e => setTravelers(e.target.value)}
                className="w-full h-11 border border-input bg-background rounded-md px-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
              >
                {['Solo', 'Couple', 'Family with kids', 'Group of friends'].map(t => (
                  <option key={t} value={t}>{t}</option>
                ))}
              </select>
            </div>
          </div>

          {error && <p className="text-sm text-red-600">{error}</p>}

          <Button
            onClick={generate}
            disabled={loading}
            className="w-full h-12 bg-blue-600 hover:bg-blue-700 text-white font-bold text-base rounded-xl"
          >
            {loading ? 'AI is preparing your list…' : 'Generate Packing List'}
          </Button>
        </CardContent>
      </Card>

      {loading && (
        <div className="flex flex-col items-center gap-4 py-16">
          <div className="w-12 h-12 border-4 border-blue-600 border-t-transparent rounded-full animate-spin" />
          <p className="text-gray-500 text-sm font-medium">AI is preparing your list…</p>
        </div>
      )}

      {result && (
        <div className="space-y-6">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div>
              <h2 className="text-xl font-bold text-gray-900">Your Packing List</h2>
              {totalItems > 0 && (
                <p className="text-xs text-gray-400 mt-0.5">{checkedCount}/{totalItems} items packed</p>
              )}
            </div>
            <div className="flex gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => window.print()}
                className="gap-1.5"
              >
                🖨️ Print
              </Button>
              <a
                href={`https://wa.me/?text=${buildWhatsAppText()}`}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 px-3 py-2 rounded-md border border-green-300 text-sm font-medium text-green-700 bg-green-50 hover:bg-green-100 transition-colors"
              >
                💬 Share
              </a>
            </div>
          </div>

          {/* Progress bar */}
          {totalItems > 0 && (
            <div className="w-full bg-gray-100 rounded-full h-2">
              <div
                className="bg-blue-600 h-2 rounded-full transition-all duration-300"
                style={{ width: `${Math.round(checkedCount / totalItems * 100)}%` }}
              />
            </div>
          )}

          <div className="grid sm:grid-cols-2 gap-4">
            {result.categories.map(cat => (
              <Card key={cat.name} className="border shadow-sm">
                <CardContent className="p-4">
                  <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
                    <span className="text-xl">{cat.icon}</span>
                    {cat.name}
                    <span className="ml-auto text-xs text-gray-400 font-normal">
                      {cat.items.filter(item => checked[`${cat.name}__${item}`]).length}/{cat.items.length}
                    </span>
                  </h3>
                  <ul className="space-y-2">
                    {cat.items.map(item => {
                      const key = `${cat.name}__${item}`
                      const done = !!checked[key]
                      return (
                        <li key={key} className="flex items-center gap-2.5">
                          <input
                            type="checkbox"
                            id={key}
                            checked={done}
                            onChange={() => toggleItem(key)}
                            className="w-4 h-4 accent-blue-600 shrink-0 cursor-pointer"
                          />
                          <label
                            htmlFor={key}
                            className={`text-sm cursor-pointer transition-all ${done ? 'line-through opacity-50 text-gray-400' : 'text-gray-700'}`}
                          >
                            {item}
                          </label>
                        </li>
                      )
                    })}
                  </ul>
                </CardContent>
              </Card>
            ))}
          </div>

          {result.tips.length > 0 && (
            <div className="space-y-2">
              <h3 className="font-semibold text-gray-900">💡 Travel Tips</h3>
              <div className="space-y-2">
                {result.tips.map((tip, i) => (
                  <div key={i} className="bg-blue-50 border border-blue-200 rounded-xl px-4 py-3 text-sm text-blue-800">
                    {tip}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

export default function PackingListPage() {
  return (
    <Suspense fallback={<div className="max-w-3xl mx-auto px-4 py-12 text-center text-gray-400">Loading…</div>}>
      <PackingListInner />
    </Suspense>
  )
}
