// ─── IATA Airport Codes for Indian Cities ────────────────────────────────────
export const IATA_CODES: Record<string, string> = {
  'mumbai': 'BOM', 'bombay': 'BOM',
  'delhi': 'DEL', 'new delhi': 'DEL',
  'bangalore': 'BLR', 'bengaluru': 'BLR',
  'chennai': 'MAA', 'madras': 'MAA',
  'hyderabad': 'HYD', 'secunderabad': 'HYD',
  'kolkata': 'CCU', 'calcutta': 'CCU',
  'goa': 'GOI', 'panaji': 'GOI', 'north goa': 'GOI', 'south goa': 'GOI',
  'kochi': 'COK', 'cochin': 'COK', 'ernakulam': 'COK',
  'pune': 'PNQ',
  'ahmedabad': 'AMD',
  'jaipur': 'JAI',
  'lucknow': 'LKO',
  'varanasi': 'VNS', 'banaras': 'VNS',
  'amritsar': 'ATQ',
  'agra': 'AGR',
  'udaipur': 'UDR',
  'jodhpur': 'JDH',
  'chandigarh': 'IXC',
  'nagpur': 'NAG',
  'indore': 'IDR',
  'bhopal': 'BHO',
  'srinagar': 'SXR',
  'jammu': 'IXJ',
  'leh': 'IXL',
  'ranchi': 'IXR',
  'patna': 'PAT',
  'guwahati': 'GAU',
  'bhubaneswar': 'BBI',
  'visakhapatnam': 'VTZ', 'vizag': 'VTZ',
  'coimbatore': 'CJB',
  'madurai': 'IXM',
  'trichy': 'TRZ', 'tiruchirappalli': 'TRZ',
  'mangalore': 'IXE', 'mangaluru': 'IXE',
  'hubli': 'HBX', 'hubballi': 'HBX',
  'aurangabad': 'IXU',
  'shirdi': 'SAG',
  'port blair': 'IXZ', 'andaman': 'IXZ',
  'imphal': 'IMF',
  'dibrugarh': 'DIB',
  'silchar': 'IXS',
  'bagdogra': 'IXB', 'darjeeling': 'IXB', 'siliguri': 'IXB',
  'raipur': 'RPR',
  'dehradun': 'DED', 'haridwar': 'DED', 'rishikesh': 'DED',
  'tirupati': 'TIR',
  'vijayawada': 'VGA',
  'rajkot': 'RAJ',
  'vadodara': 'BDQ', 'baroda': 'BDQ',
  'surat': 'STV',
  'jabalpur': 'JLR',
  'gwalior': 'GWL',
  'allahabad': 'IXD', 'prayagraj': 'IXD',
  'gorakhpur': 'GOP',
  'mysore': 'MYQ', 'mysuru': 'MYQ',
  'kozhikode': 'CCJ', 'calicut': 'CCJ',
  'thiruvananthapuram': 'TRV', 'trivandrum': 'TRV',
  'trissur': 'TCR', 'thrissur': 'TCR',
}

// ─── IRCTC Station Codes for Indian Cities ───────────────────────────────────
export const IRCTC_CODES: Record<string, string> = {
  'mumbai': 'CSTM', 'bombay': 'CSTM',
  'delhi': 'NDLS', 'new delhi': 'NDLS',
  'bangalore': 'SBC', 'bengaluru': 'SBC',
  'chennai': 'MAS', 'madras': 'MAS',
  'hyderabad': 'HYB', 'secunderabad': 'SC',
  'kolkata': 'HWH', 'calcutta': 'HWH',
  'goa': 'MAO', 'madgaon': 'MAO', 'north goa': 'MAO', 'south goa': 'MAO', 'panaji': 'MAO',
  'kochi': 'ERS', 'cochin': 'ERS', 'ernakulam': 'ERS',
  'pune': 'PUNE',
  'ahmedabad': 'ADI',
  'jaipur': 'JP',
  'lucknow': 'LKO',
  'varanasi': 'BSB', 'banaras': 'BSB',
  'amritsar': 'ASR',
  'agra': 'AGC',
  'udaipur': 'UDZ',
  'jodhpur': 'JU',
  'chandigarh': 'CDG',
  'nagpur': 'NGP',
  'indore': 'INDB',
  'bhopal': 'BPL',
  'jammu': 'JAT',
  'ranchi': 'RNC',
  'patna': 'PNBE',
  'guwahati': 'GHY',
  'bhubaneswar': 'BBS',
  'visakhapatnam': 'VSKP', 'vizag': 'VSKP',
  'coimbatore': 'CBE',
  'madurai': 'MDU',
  'trichy': 'TPJ', 'tiruchirappalli': 'TPJ',
  'mangalore': 'MAQ', 'mangaluru': 'MAQ',
  'mysore': 'MYS', 'mysuru': 'MYS',
  'hubli': 'UBL', 'hubballi': 'UBL',
  'aurangabad': 'AWB',
  'surat': 'ST',
  'vadodara': 'BRC', 'baroda': 'BRC',
  'raipur': 'R',
  'dehradun': 'DDN',
  'haridwar': 'HW',
  'rishikesh': 'RKSH',
  'allahabad': 'ALD', 'prayagraj': 'ALD',
  'gorakhpur': 'GKP',
  'gwalior': 'GWL',
  'jabalpur': 'JBP',
  'darjeeling': 'NJP', 'siliguri': 'NJP', 'bagdogra': 'NJP',
  'ajmer': 'AII',
  'solapur': 'SUR',
  'nashik': 'NK',
  'kolhapur': 'KOP',
  'tirupati': 'TPTY',
  'vijayawada': 'BZA',
  'rajkot': 'RJT',
  'shirdi': 'SNSI',
  'kozhikode': 'CLT', 'calicut': 'CLT',
  'thiruvananthapuram': 'TVC', 'trivandrum': 'TVC',
  'nagercoil': 'NCJ',
  'salem': 'SA',
  'dhanbad': 'DHN',
  'jamshedpur': 'TATA',
  'rourkela': 'ROU',
}

// ─── Airline display names ────────────────────────────────────────────────────
export const AIRLINE_NAMES: Record<string, string> = {
  '6E': 'IndiGo',
  'AI': 'Air India',
  'SG': 'SpiceJet',
  'UK': 'Vistara',
  'QP': 'Akasa Air',
  'IX': 'Air India Express',
  'I5': 'Air Asia India',
  'G8': 'GoAir',
  'S5': 'Star Air',
  'EK': 'Emirates',
  'QR': 'Qatar Airways',
  'SQ': 'Singapore Airlines',
  'FZ': 'flydubai',
  '9W': 'Jet Airways',
  'LH': 'Lufthansa',
  'BA': 'British Airways',
}

// ─── Gradient colours per hotel type ─────────────────────────────────────────
export const HOTEL_GRADIENTS: Record<string, string> = {
  luxury:  'from-purple-500 to-pink-600',
  comfort: 'from-blue-400 to-indigo-500',
  budget:  'from-green-400 to-teal-500',
  hostel:  'from-yellow-400 to-orange-500',
  villa:   'from-cyan-400 to-blue-500',
  resort:  'from-emerald-400 to-cyan-600',
  default: 'from-gray-400 to-slate-500',
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
export function getIATACode(city: string): string | null {
  return IATA_CODES[city.toLowerCase().trim()] ?? null
}

export function getIRCTCCode(city: string): string | null {
  return IRCTC_CODES[city.toLowerCase().trim()] ?? null
}

/** Rough straight-line distance in km between two Indian cities (for bus estimates) */
const ROUTE_DISTANCES: Record<string, number> = {
  'mumbai-pune': 150, 'pune-mumbai': 150,
  'mumbai-goa': 600, 'goa-mumbai': 600,
  'delhi-jaipur': 280, 'jaipur-delhi': 280,
  'delhi-agra': 200, 'agra-delhi': 200,
  'delhi-chandigarh': 250, 'chandigarh-delhi': 250,
  'delhi-lucknow': 550, 'lucknow-delhi': 550,
  'bangalore-mysore': 150, 'mysore-bangalore': 150,
  'bangalore-coimbatore': 360, 'coimbatore-bangalore': 360,
  'bangalore-goa': 600, 'goa-bangalore': 600,
  'bangalore-chennai': 350, 'chennai-bangalore': 350,
  'hyderabad-bangalore': 570, 'bangalore-hyderabad': 570,
  'hyderabad-goa': 680, 'goa-hyderabad': 680,
  'kolkata-bhubaneswar': 440, 'bhubaneswar-kolkata': 440,
  'mumbai-ahmedabad': 530, 'ahmedabad-mumbai': 530,
  'chennai-pondicherry': 160, 'pondicherry-chennai': 160,
}

export function getApproxDistanceKm(from: string, to: string): number {
  const key = `${from.toLowerCase()}-${to.toLowerCase()}`
  return ROUTE_DISTANCES[key] ?? 500
}
